services:

  # MONGO DB
  mongo:
    image: mongo:latest
    container_name: my-mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass

  # MONGO-EXPRESS
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017

  # CUSTOMER APP
  mongo-docker-api:
    image: mongo-docker-api:latest
    container_name: mongo-docker-api
    depends_on:
      - mongo-express           # It comes up last
    ports:
      - 8080:8080
    environment:
      - MONGODB_URL:mongodb://admin:pass@mongo:27017/
      - ASPNETCORE_HTTP_PORTS:8080     


volumes:
  mongodb_data:
    external: true
